{
login: "baileyhood",
id: 16865671,
avatar_url: "https://avatars.githubusercontent.com/u/16865671?v=3",
gravatar_id: "",
url: "https://api.github.com/users/baileyhood",
html_url: "https://github.com/baileyhood",
followers_url: "https://api.github.com/users/baileyhood/followers",
following_url: "https://api.github.com/users/baileyhood/following{/other_user}",
gists_url: "https://api.github.com/users/baileyhood/gists{/gist_id}",
starred_url: "https://api.github.com/users/baileyhood/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/baileyhood/subscriptions",
organizations_url: "https://api.github.com/users/baileyhood/orgs",
repos_url: "https://api.github.com/users/baileyhood/repos",
events_url: "https://api.github.com/users/baileyhood/events{/privacy}",
received_events_url: "https://api.github.com/users/baileyhood/received_events",
type: "User",
site_admin: false,
name: "Bailey Hood",
company: null,
blog: null,
location: null,
email: null,
hireable: null,
bio: null,
public_repos: 11,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2016-01-24T15:34:52Z",
updated_at: "2016-02-11T16:32:38Z"
}
